

# Replication Controller for springapp
apiVersion: v1
kind: Deployment
metadata:
  name: spring-controller
spec:
  replicas: 1
  selector:
    app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - image: dockerhandson/spring-boot-mongo
        name: springboot
        ports:
        - containerPort: 8080  
        env:
        - name: MONGO_DB_HOSTNAME
          valueFrom: 
            secretKeyRef:
              name: springboot-secret
              key: hostname
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: springapp-secret
              key: username 
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: springapp-secret
              key: password       
---
# Node Port Service For SpringApp
apiVersion: v1
kind: Service
metadata:
  name: springboot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: springboot
---
# Mongo RC with host path Volume
apiVersion: v1
kind: StatefulSet
metadata:
  name: mongo-controller
spec:
  replicas: 1
  selector:
    app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: springapp-secret
              key: username 
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: springapp-secret
              key: password 
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        hostPath:
         path: /tmp/dbbackup
---
# Mongo Node Port RC
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
